### PR TITLE
Jnf

### LINKED ISSUE #8: Job Notification Form - Implement the job notification form to be filled by companies
* Implement the JNF form
* Check should be done in the frontend if required fields are filled

Individual pages can be finished:
- [x] Page 1
- [x] Page 2
- [x] Page 3
- [x] Page 4
- [x] Page 5

To be added : 6th page for email verification occours

jnf_page1
jnf_page2
jnf_page3
jnf_page4
jnf_page5

### PR DESCRIPTION
**Pull request by gowtham3105**
- Has JNF Component 
 - Route setup for JNF
 - Contains @ModernOctave Code
 
closes #8

### CODE REVIEW

**Comment by AkM-2018** [comment]
Looks good to me. Working as expected.

- Submit button is kept disabled. Is it on purpose?
-  Also what about the permanent position of the jnf. We'll just give links to the company rgt?

**Comment by ModernOctave** [comment]
> Submit button is kept disabled. Is it on purpose?

Yeah this is part of the validation, once all required fields are filled it should be enabled

**Comment by AkM-2018** [comment]
> > Submit button is kept disabled. Is it on purpose?
> 
> Yeah this is part of the validation, once all required fields are filled it should be enabled

Oh sorry. Seems like a missed a field. 
Submit button is working! Is code for the email also completed?

**Review by AkM-2018 — DISMISSED** [review]
Can be merged!

**Review by CDC-IITDH — APPROVED** [review]

**Pull request merged**
