### PR TITLE
Add Search Bar

### PR DESCRIPTION
**Pull request by rudrakshsattabhayya**

### CODE REVIEW

**Comment by rudrakshsattabhayya** [comment]
#6

**Comment by AkM-2018** [comment]
PR looks great. Amazing work @karthikmurakonda. 

Some upgrades and fixes for later(not for this PR):
- Clicking from the suggestion box does not filter results currently.
- If I want to search for "Apple" say and I misspell it as "Applr" and search, then again correct it as "Apple" and search, it doesnt show results, eventhough results might be there. (Just observed it. Might be an implementation issue)

PR can be merged, but might result in merge conflicts in Dashboard.js and App.js

**Comment by karthikmurakonda** [comment]
> If I want to search for "Apple" say and I misspell it as "Applr" and search, then again correct it as "Apple" and search, it doesnt show results, eventhough results might be there. (Just observed it. Might be an implementation issue)

yeah its implementation issue only. Fixed now.

**Comment by karthikmurakonda** [comment]
> PR can be merged, but might result in merge conflicts in Dashboard.js and App.js

I have merged master to this branch earlier. This branch is not behind master

**Comment by gowtham3105** [comment]
- Updated Admin Dashboard Cards
- Added New Job Notifications tab for new offers which are yet to be approved
screencapture-localhost-3000-admin-2021-12-16-21_54_33 (1)

**Review by gowtham3105 — DISMISSED** [review]

**Review by gowtham3105 — APPROVED** [review]
checked and approved

**Pull request merged**
