### PR TITLE
Add PPO

### LINKED ISSUE #42: Add PrePlacement Offer
- Create a Simple Form to add PPO in the database
- Collect the data and submit it in a Api call
- Required data
    - student_id
    - company name
    - compensation gross
    - compensation details (optional leave blank by default)
    - designation
    - accepted (true or false, whether offer is accepted by student or not)

### PR DESCRIPTION
**Pull request by gowtham3105**
- added add PPO component 
- can be clicked form nav bar
closes #42

### CODE REVIEW

**Comment by gowtham3105** [comment]
screencapture-localhost-3000-admin-2021-12-17-23_32_09

**Comment by AkM-2018** [comment]
API endpoint is set to localhost again XD

**Comment by gowtham3105** [comment]
Updated API Endpoint

**Review by AkM-2018 — APPROVED** [review]
Can be merged.

**Pull request merged**
