### PR TITLE
pagination bar

### PR DESCRIPTION
**Pull request by Abhishek28112002**

### CODE REVIEW

**Comment by CDC-IITDH** [comment]
Use [material ui](https://mui.com/material-ui/react-pagination/). That has inbuilt styling

**Review by CDC-IITDH — CHANGES_REQUESTED** [review]
Changes required

**Comment by gowtham3105** [comment]
Resolve the merge conflicts

**Review by karthikmurakonda — DISMISSED** [review]

**Review by gowtham3105 — APPROVED** [review]

**Comment by gowtham3105** [comment]
resolve the merge conflicts and merge it

**Review by gowtham3105 — APPROVED** [review]

**Pull request merged**
